### ISSUE TITLE
Implement a keystroke to display the toolbar in a collapsed selection

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-editor-balloon-toolbar#3]
It would certainly:
1. Help our users change the block type without making the actual selection.
2. Improve the accessibility of the application.

A follow-up of #1.

**Comment by oleq** [comment]
I'm wondering if <kbd>Alt</kbd>+<kbd>F10</kbd> is the right keystroke to show and focus the toolbar in such situation. Or maybe a new keystroke is needed?

**Comment by Reinmar** [comment]
For me it could be the good old <kbd>Alt</kbd>+<kbd>F10</kbd>.

**Comment by oleq** [comment]
The implementation in https://github.com/ckeditor/ckeditor5-editor-balloon-toolbar/tree/t/3, awaiting https://github.com/ckeditor/ckeditor5-ui/issues/263 to close.
